openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: domain ที่เก็บข้อมูลนาฬิกาสุขภาพ บน vm
    url: http://203.151.164.229:9001
  - description: domain ที่เก็บข้อมูลนาฬิกาสุขภาพ ใน local
    url: http://127.0.0.1:9000
info:
  description: This is a simple API for iHealth ดูเอกสารเพิ่มเติม https://docs.google.com/document/d/1KgF2ULEIZnBwbLFsgN06lk50umegJIWFvqX-lfht2Aw/edit
  version: "1.0.0"
  title: Simple API for iHealth
  contact:
    email: marwan17705@gmail.com
tags:
  - name: developers
    description: Operations available to regular developers
  - name: admin
    description: Operations available to admin

paths:
  /api/v1/api_server/measurement:
    post: 
      tags:
        - developers
      summary: สั่งวัดสุขภาพ
      description: |
        สั่งวัดสุขภาพ <br>
        event ประกอบด้วย test_heart_rate, test_spo2, test_body_temp
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/basic'
            example: 
              "event": "test_heart_rate"
              "dest": 
                  "thing_id": "f041dece-af13-4567-987f-b18b70c08808"
  /api/v1/api_server/setting:
    post: 
      tags:
        - developers
      summary: ตั้งค่าอุปกรณ์นาฬิกา
      description: |
        ตั้งค่าอุปกรณ์นาฬิกา  <br>
        event ประกอบด้วย <br>
        - set_sos_number คือ ตั้งค่า sos <br>
        - set_phone_book คือ ตั้งค่าเบอร์ผู้ติดต่อ <br>
        - set_working_mode คือ ตั้งค่าโหมดการทำงานของนาฬิกา <br>
        - set_fall_switch คือ ตั้งค่าเปิดปิดการแจ้งเตือนการล้ม <br>
        - set_auto_measurement คือ การตั้งค่าเพื่อวัดค่าสุขภาพอัตโนมัติทุก ๆ Interval ที่กำหนด ค่าสุขภาพประกอบด้วยอุณหภูมิร่างกาย และอัตราการเต้นของหัวใจ <br>
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      requestBody:
        content:
          application/json:              
            schema:
              $ref: '#/components/schemas/setting'
            example: 
              "event": "set_sos_number"
              "dest": 
                  "thing_id": "f041dece-af13-4567-987f-b18b70c08808"
              "data": 
                "phone_num": 
                  - "0877967516"
                  - "0883971144"
                  - "191"
  /api/v1/api_server/location:
    post: 
      tags:
        - developers
      summary: สั่งวัดตำแหน่งอุปกรณ์ ณ ปัจจุบัน
      description: |
        สั่งวัดสุขภาพ <br>
        event ประกอบด้วย realtime_locating
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/basic'
            example: 
              "event": "realtime_locating"
              "dest": 
                  "thing_id": "f041dece-af13-4567-987f-b18b70c08808"
  /api/v1/api_server/device/connection:
    get: 
      tags:
        - developers
      summary: แสดงอุปกรณ์ทั้งหมดที่กำลังเชื่อมต่อ API server
      description: |
        แสดงอุปกรณ์ทั้งหมดที่กำลังเชื่อมต่อ API server <br>
        status ประกอบด้วย connect, disconnect, all
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
          
      parameters:
        - name: status
          in: query
          description: device's status
          required: true
          schema:
            type: string
  /api/v1/api_server/command/write:
    post: 
      tags:
        - developers
      summary: เขียน Command ไปยังอุปกรณ์ l16 โดยตรง
      description: |
        เขียน Command ไปยังอุปกรณ์ l16 โดยตรง <br>
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/basic'
            example: |
              {
                  "event": "write_command",
                  "data": {
                      "command": "IWBPXY,353456789012345,080835#" 
                  },
                  "dest": {
                      "imei": "865513041165769"
                  }
              }
  /api/v2/api_server/device/health/current:
    get: 
      tags:
        - developers
      summary: ดึงเอาค่าสุขภาพ 3 ค่าในปัจจุบัน
      description: |
         ดึงเอาค่าสุขภาพ 3 ค่าในปัจจุบัน ตามอุปกรณ์ ((body_temperature,heart_rate,blood_oxygen)
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      parameters:
        - name: thing_id
          in: query
          description: device's thing_id
          required: true
          example: f041dece-af13-4567-987f-b18b70c08808
          schema:
            type: string
  /api/v2/api_server/device/health/report:
    get: 
      tags:
        - developers
      summary: ดึงค่าข้อมูลสุขภาพย้อนหลัง
      description: |
         ค่าสุขภาพประกอบด้วย ((body_temperature,heart_rate,blood_oxygen) <br>
          | Parameter | data type | Description |
          |-----|-----|-------|
          |type[] |array string |ชนิดของข้อมูลสุขภาพที่ร้องขอ (body_temperature,heart_rate,blood_oxygen) |
          |thing_id |string |id ของอุปกรณ์ |
          |start_date |string |เวลาเริ่มต้นร้องขอข้อมูล (2022-09-28) |
          |end_date |string |เวลาสิ้นสุดร้องขอข้อมูล (2022-09-27) |
          | | | |
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      parameters:
        - name: type
          in: query
          description: device's type
          required: true
          schema:
            type: array
            items:
              type: string
            example: ['body_temperature','heart_rate']
        - name: thing_id
          in: query
          description: device's thing_id
          required: true
          example: f041dece-af13-4567-987f-b18b70c08808
          schema:
            type: string
        - name: start_date
          in: query
          description: start_date
          required: true
          example: '2022-09-27'
          schema:
            type: string
        - name: end_date
          in: query
          description: end_date
          required: true
          example: '2022-09-28'
          schema:
            type: string
  /api/v2/api_server/device/statistic/current:
    get: 
      tags:
        - developers
      summary: ดึงเอาค่าสถิติ 3 ค่าในปัจจุบัน
      description: |
         ดึงเอาค่าสถิติ 3 ค่าในปัจจุบัน ตามอุปกรณ์ (SOS,fall_down,fall_ok)
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      parameters:
        - name: thing_id
          in: query
          description: device's thing_id
          required: true
          example: f041dece-af13-4567-987f-b18b70c08808
          schema:
            type: string
  /api/v2/api_server/device/statistic/report:
    get: 
      tags:
        - developers
      summary: ดึงเอาค่าสถิติย้อนหลัง
      description: |
         เอาค่าสถิติประกอบด้วย (SOS,fall_down,fall_ok) <br>
          | Parameter | data type | Description |
          |-----|-----|-------|
          |type[] |array string |ชนิดของข้อมูลสถิติที่ร้องขอ (SOS,fall_down,fall_ok) |
          |thing_id |string |id ของอุปกรณ์ |
          |start_date |string |วันเริ่มต้นร้องขอข้อมูล (2022-09-28) |
          |end_date |string |วันสิ้นสุดร้องขอข้อมูล (2022-09-27) |
          | | | |
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      parameters:
        - name: type
          in: query
          description: device's type
          required: true
          schema:
            type: array
            items:
              type: string
            example: ['SOS','fall_down']
        - name: thing_id
          in: query
          description: device's thing_id
          required: true
          example: f041dece-af13-4567-987f-b18b70c08808
          schema:
            type: string
        - name: start_date
          in: query
          description: start_date
          required: true
          example: '2022-09-27'
          schema:
            type: string
        - name: end_date
          in: query
          description: end_date
          required: true
          example: '2022-09-28'
          schema:
            type: string
  /api/v2/api_server/device/location/current:
    get: 
      tags:
        - developers
      summary: ค่าข้อมูลตำแหน่ง
      description: |
         ค่าข้อมูลตำแหน่ง <br>
          | Parameter | data type | Description |
          |-----|-----|-------|
          |thing_id[] |array string |id ของอุปกรณ์|
          | | | |
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      parameters:
        - name: thing_id
          in: query
          description: device's thing_id
          required: true
          schema:
            type: array
            items:
              type: string
            example: ['f041dece-af13-4567-987f-b18b70c08808','1c786899-66b7-4f12-a930-8d3a713b0725']
  /api/v2/api_server/device/location/report:
    get: 
      tags:
        - developers
      summary: ดึงเอาค่าข้อมูลตำแหน่งย้อนหลัง
      description: |
         ดึงเอาค่าข้อมูลตำแหน่งย้อนหลัง<br>
          | Parameter | data type | Description |
          |-----|-----|-------|
          |thing_id |string |id ของอุปกรณ์ |
          |start_dt |string |เวลาเริ่มต้นร้องขอข้อมูล (2022-10-07 11:01:41) |
          |end_dt |string |เวลาสิ้นสุดร้องขอข้อมูล (2022-11-28 11:01:41) |
          | | | |
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      parameters:
        - name: thing_id
          in: query
          description: device's thing_id
          required: true
          example: f041dece-af13-4567-987f-b18b70c08808
          schema:
            type: string
        - name: start_dt
          in: query
          description: start_date
          required: true
          example: '2022-10-07 11:01:41'
          schema:
            type: string
        - name: end_dt
          in: query
          description: end_date
          required: true
          example: '2022-11-28 11:01:41'
          schema:
            type: string
  /api/v1/api_server/device/restart:
    post: 
      tags:
        - developers
      summary: api เพื่อสั่งให้อุปกรณ์ restart ตัวมันเอง
      description: |
        api เพื่อสั่งให้อุปกรณ์ restart ตัวมันเอง <br>
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/basic'
            example: 
              "event": "restart_device"
              "dest": 
                  "thing_id": "f041dece-af13-4567-987f-b18b70c08808"
  /api/v1/api_server/device/register/single:
    post: 
      tags:
        - admin
      summary: เพิ่มอุปกรณ์ 1 ตัว
      description: |
        เพิ่ม อุปกรณ์ 1 ตัว ไปยังฐานข้อมูล api server <br>
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
            example: |
              {
                  "device_id":"123",
                  "model":"l16",
                  "brand":"PTPL"

              }
    delete:
      tags:
        - admin
      summary: ลบอุปกรณ์ 1 ตัว
      description: |
         ลบอุปกรณ์ 1 ตัว จากฐานข้อมูล api server (NOT RELEASES) <br>
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway
      parameters:
        - name: thing_id
          in: query
          description: device's thing_id
          required: true
          example: f041dece-af13-4567-987f-b18b70c08808
          schema:
            type: string
  /api/v2/api_server/device/config:
    post: 
      tags:
        - admin
      summary: ตั้งค่าอุปกรณ์การทำงาน 1 ตัว
      description: |
        ตั้งค่าอุปกรณ์ 1 ตัว  <br>
      security:
        - tokenWebhook: []
      responses:
        '200':
          description: search results matching criteria
        '401':
          description: Unauthorized
        '502':
          description: Bad Gateway  
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configDevice'
            example: 
              "event": "write_command"
              "dest": 
                  "imei": "865513041165769"
              config:
                working_mode: "08"
                gps_enable: 1
                gps_interval: 15
                health_interval: 60
                fall_down_enable: 1
              
components:
  schemas:
    basic:
      type: object
      required: 
        - event
        - dest
      properties:  
        event:
          type: string
        dest:
          type: object
          properties:
            imei:
              type: string
    setting:
      type: object
      required: 
        - event
        - dest
        - data
      properties:  
        data:
          type: object
          description: |
           - event set_sos_number ใช้ data <br>
              "data": {
                  "phone_num": [
                      "0877967516",
                      "0883971144",
                      "191"
                  ]} <br>
           - event set_phone_book ใช้ data <br>
              "data": [
                {
                    "phone_num":"0877967516",
                    "contact_name":"Peth"
                },
                {
                    "phone_num":"0883971144",
                    "contact_name":"Toon"
                },
                {
                    "phone_num":"191",
                    "contact_name":"Police"
                }
              ]  <br>  
           - event set_working_mode ใช้ data <br>
              "data": {
                  "working_mode": 1
              } <br>
              <br>
           - event set_working_mode โหมด 8 ใช้ data <br>
              "data": {
                  "working_mode": 8,
                  "interval_gps": 30,
                  "flag_gps": 1,
              }
              <br>
              interval_gps มีหน่วยเป็น วินาที
           - event set_fall_switch ใช้ data <br>
              "data": {
                  "fall_alarm_switch": 1
              }
              <br>
           - event write_command ใช้ data <br>
              "data": {
                  "command": "IWBPXY,353456789012345,080835#"
              }
              <br>
           - event set_auto_measurement ใช้ data <br>
              "data": {
                  "set_auto_measurement":1,
                  "interval": 10
              }<br>
              ตาราง parameter
              <br>
              | Parameter | data type | Description |
              |-----|-----|-------|
              |set_auto_measurement |bool |การเปิด - ปิด โหมดการวัดค่าสุขภาพอัตโนมัติ (1 คือ เปิด  หรือ 0 คือ ปิด) |
              |interval |int |ความถี่ในการวัดค่าสุขภาพ (หน่วย นาที) |
              |fall_alarm_switch |int | 1 คือ เปิด หรือ 0 คือ ปิด |
              |working_mode |int |อ้างอิง https://docs.google.com/document/d/1p1VOn9U-5s7C88eEuu3oiwZVy4p-AxHRaLp9HBzKWv8/edit |
              | | | |

        dest:
          type: object
          properties:
            thing_id:
              type: string
        event:
          type: string 
    register:
      type: object
      required: 
        - "device_id"
        - "model"
        - "brand"
      properties:  
        device_id:
          type: string
        model:
          type: string
        brand:
          type: string
    configDevice:
      type: object
      required: 
        - event
        - dest
      properties:  
        event:
          type: string
        dest:
          type: object
          properties:
            imei:
              type: string
        config:
          type: object
          properties:  
            working_mode:
              type: string
            gps_enable:
              type: integer
            gps_interval:
              type: integer
            health_interval:
              type: integer
            fall_down_enable:
              type: integer          
  securitySchemes:
    tokenWebhook:     
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: x-api-key  # name of the header, query parameter or cookie
# https://json-to-swagger.netlify.app/
